const products = [
    {
        _id: "1",
        name: "Apple AirPods Pro(2nd Gen) Wireless Bluetooth Headphones",
        image: [
            "/images/airpods-pro.jpg",
            "/images/airpods-pro(1).jpg",
            "/images/airpods-pro(2).jpg",
            "/images/airpods-pro(3).jpg",
            "/images/airpods-pro(4).jpg",
        ],
        description:
            "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
        brand: "Apple",
        category: "Electronics",
        price: 18999,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: "2",
        name: "iPhone 15 Pro 256GB Memory",
        image: [
            "/images/iphone-15.jpg",
            "/images/iphone-15(1).jpg",
            "/images/iphone-15(2).jpg",
            "/images/iphone-15(3).jpg",
            "/images/iphone-15(4).jpg",
            "/images/iphone-15(5).jpg",
        ],
        description:
            "Introducing the iPhone 15 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
        brand: "Apple",
        category: "Electronics",
        price: 141900,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
    },
    {
        _id: "3",
        name: "Canon EOS R6 Mark II RF24-105mm F4 L camera with USM KIT",
        image: [
            "/images/camera.jpg",
            "/images/camera(1).jpg",
            "/images/camera(2).jpg",
            "/images/camera(3).jpg",
            "/images/camera(4).jpg",
        ],
        description:
            "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
        brand: "Cannon",
        category: "Electronics",
        price: 764999,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
    },
    {
        _id: "4",
        name: "Sony PS5 Standard DualSense bundle",
        image: ["/images/PS5.jpg", "/images/PS5(1).jpg", "/images/PS5(2).jpg"],
        description:
            "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
        brand: "Sony",
        category: "Electronics",
        price: 58990,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: "5",
        name: "Logitech G304 Lightspeed Wireless Gaming Mouse",
        image: [
            "/images/mouse.jpg",
            "/images/mouse(1).jpg",
            "/images/mouse(2).jpg",
            "/images/mouse(3).jpg",
            "/images/mouse(4).jpg",
            "/images/mouse(5).jpg",
            "/images/mouse(6).jpg",
            "/images/mouse(7).jpg",
            "/images/mouse(8).jpg",
        ],
        description:
            "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
        brand: "Logitech",
        category: "Electronics",
        price: 3095,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
    },
    {
        _id: "6",
        name: "Amazon Echo Dot (5th Gen)",
        image: [
            "/images/alexa.jpg",
            "/images/alexa(1).jpg",
            "/images/alexa(2).jpg",
            "/images/alexa(3).jpg",
            "/images/alexa(4).jpg",
            "/images/alexa(5).jpg",
        ],
        description:
            "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
        brand: "Amazon",
        category: "Electronics",
        price: 5499,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
    },
];

export default products;
